sync check-file-names.yml across branches

diff --git a/.github/workflows/check-file-names.yml b/.github/workflows/check-file-names.yml
--- a/.github/workflows/check-file-names.yml
+++ b/.github/workflows/check-file-names.yml
@@ -16,9 +16,11 @@ jobs:
       - uses: actions/checkout@v4
 
       # Runs a set of commands using the runners shell
-      - name: Check directory names
-        continue-on-error: true
+      - name: Check file and directory names
         run: |
-	    echo "hi"
-	    find . -type d
-	  
+          WRONG_NAMES="$(find . | grep -v -e '/\.' -e '.*\.import' | egrep -v '^[\./_[:lower:]]+$')"
+          if [ "$WRONG_NAMES" ] ; then
+             echo "::error::All files and directories should be named using snake_case"
+             echo "$WRONG_NAMES"
+             exit 1
+          fi
